name: 'Architus staging comment action'
description: 'Adds comments to archit.us pull requests with build information/staging links'
inputs:
  mode:
    description: 'Operation mode (either "pre" or "post"); used to display different messages during/after build'
    default: 'post'
    required: false
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/cleanup.js'
