name: 'Architus Upload API Client'
description: 'Uploads build archives to the Architus staging upload API'
inputs:
  archive-path:
    description: 'Path of the build archive'
    required: true
  token:
    description: 'Upload API token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
